### ISSUE TITLE
Guarantee event loop isolation?

### ISSUE THREAD

**Issue by domenic** [WICG/origin-isolation#16]
It's recently come to my attention that all implementations have the ability to have separate event loops within the same thread.

Also, separate vs. shared event loops is observable. (In a probabilistic fashion: you can queue up a bunch of stuff and have it match the expected sequence 100% of the time in a shared event loop, whereas the longer the sequence gets, the more unlikely it would be to match given separate, racing event loops.)

I believe the HTML spec currently gives a lot of leeway for sharing event loops or not. (At a glance: "user agents may share an event loop across similar-origin window agents.") If I am reading correctly, the only event loops that are guaranteed to be separate are worker event loops.

I wonder if we want to use origin isolation as a way for sites to guarantee separate (window) event loops, since it's a common developer desire, and apparently it's implementable in all architectures.

Alternately, this might not be the right place to do that. Web developers often want to guarantee separate event loops even for same-origin pages. A proposal that meets that use case would be [disallowdocumentaccess](https://github.com/dtapuska/documentaccess) or some evolution of it, which allows creating a guaranteed separate event loop via `<iframe disallowdocumentaccess>` or `<iframe domworker>` or similar. Maybe we should leave guaranteed event loop isolation to workers/"DOM workers" of that sort.

Credit to @dtapuska and @chrishtr for the discussion which spawned this insight.

**Comment by annevk** [comment]
I'd love HTML to require that agents and event loops are 1:1 and maybe even merge the concepts. (But I suspect you know that already. 😊)

**Comment by domenic** [comment]
I opened https://github.com/whatwg/html/issues/5352 on making agents and event loops 1:1.

However it occurs to me that we may still want a similar hint in origin isolation. What people are really getting at is not necessarily event loop isolation, but parallelism (traditionally via separate threads or processes). Maybe "parallelism" is the better hint to use, instead of specific spec concepts like event loops.

**Comment by annevk** [comment]
What if the browser is resource-constrained and cannot guarantee whatever we'd like it to do? Is that reason to crash the page, carry on without guarantees, or do something else?

**Comment by domenic** [comment]
So far everything is just a hint. (Even `sidechannel-protection`.) So "carry on without guarantees" is the plan.

**Comment by annevk** [comment]
Okay. From that perspective, separate agents is effectively a parallelism hint, per ECMAScript.

**Comment by domenic** [comment]
Good point. So I guess parallelism just gets rolled into the "basic" origin isolation idea. Which is I guess where this thread started.

**Comment by domenic** [comment]
Hmm, I went to write up a PR for this, and I'm no longer sure. https://tc39.es/ecma262/#sec-agents says

> An agent's executing thread executes a job on the agent's execution contexts independently of other agents, except that an executing thread may be used as the executing thread by multiple agents, provided none of the agents sharing the thread have an Agent Record whose [[CanBlock]] property is true.
>
> Note 1 Some web browsers share a single executing thread across multiple unrelated tabs of a browser window, for example.

([[CanBlock]] is false for window agents.)

So, I'm feeling like maybe we do want a parallelism hint after all?

**Comment by annevk** [comment]
I had forgotten about [[CanBlock]] impacting guaranteed forward progress. That's interesting. Yeah, I think in that case it would be appropriate.

(I wonder if that's the only instance where the ECMAScript specification tacitly admits the possibility of multiple agent clusters. I suppose there will be a few more places.)
