### ISSUE TITLE
Explain relation to COOP/COEP

### ISSUE THREAD

**Issue by domenic** [WICG/origin-isolation#2]
Especially because they can cause isolations via a new browsing context group. In that regard the big difference is that COOP/COEP only apply to top-level navigations, so cannot be used for isolating iframes from their parents or isolating parents from iframes.

**Comment by annevk** [comment]
It's a bit more subtle, as cross-origin frames (including same-site) do have to opt-in to be part of COOP+COEP.

**Comment by domenic** [comment]
I added a section at https://github.com/domenic/origin-isolation#adjacent-work but I very well may have gotten some details wrong. Your review would be much appreciated.

**Comment by annevk** [comment]
Looks pretty solid to me, thanks. (I'm still a little worried about sites being able to game the hinting, but that's not directly related.)
