### ISSUE TITLE
User-agent-wide origin isolation

### ISSUE THREAD

**Issue by annevk** [WICG/origin-isolation#3]
The current setup might lead to one browsing context group (BCG) having origin isolation for A and another BCG not having it. This isn't inherently problematic, but I wonder if it might be problematic if we want to build things on top of this going forward. I guess the things we build on top would always have to be agent cluster restricted. I suspect that might be worth calling out.

And perhaps there's some alternative to this that I overlooked.

**Comment by domenic** [comment]
I discuss this in https://github.com/domenic/origin-isolation#the-browsing-context-group-scope-of-isolation. I'd love your thoughts there.

In Chromium right now our current implementation is somewhere between user-agent-wide and per-BCG. In particular, there is a user-agent wide list of isolated origins, which can only grow, and never shrink. However, BCGs are not retroactively partitioned, if a new origin gets added to this list. So e.g. you can have one BCG with site isolation and another with origin isolation, if the origin isolation policy was applied after loading the first and before loading the second.

It would certainly be much easier for us to stick to this model, so if we think that's a good idea, then let's discuss :). But my feeling is that, given that retroactive partitioning seems very hard, and the web developer-facing downside of requiring a UA restart to un-do origin isolation, the BCG-scoped model is more coherent.

**Comment by annevk** [comment]
To make it more concrete, what I was thinking of is that in the future there might be a new object Z:

* It would be bad if Z could be shared with a different origin.
* It would be annoying if Z could not be shared across tabs.

Z would require UA-wide origin isolation, unless you drop the second requirement.

However, writing this down I realize this could work, by making serializing fail based on whether origin isolation is enabled for the tab or not, so maybe per-tab (bcg) is sufficient even for Z.

**Comment by annevk** [comment]
(I guess there's also a question hidden here about whether UAs should put a site window agent and an origin window agent in the same process. That might be worth some words in a security considerations section.)

**Comment by domenic** [comment]
> (I guess there's also a question hidden here about whether UAs should put a site window agent and an origin window agent in the same process. That might be worth some words in a security considerations section.)

Do you think this is a specific thing to worry about and call out, or is it just a special case of the more general "ideally, browsers should split up everything into as many processes as possible, using the new freedom that origin isolation allows"?

That is, I'm not sure why encouraging splitting `Site{https://example.com}` and `Origin{https://example.com}` is specifically worth calling out, versus encouraging splitting `Site{https://example.com}` and `Site{https://example.org}`, or splitting `Origin{https://a.example.com}` and `Origin{https://b.example.com}`.

**Comment by domenic** [comment]
Closing for now, but happy to reopen if you think we should specifically call that out!

**Comment by annevk** [comment]
At this point I'm hoping that any such Z can require COOP+COEP.
