### ISSUE TITLE
Timing attacks on the browsing context group store

### ISSUE THREAD

**Issue by annevk** [WICG/origin-isolation#33]
While writing down https://github.com/whatwg/html/issues/5701 I got worried that the browsing context group origin cache could be attacked and end up leaking history. It might well be observable whether something is origin-isolated or not.

cc @arturjanc

**Comment by domenic** [comment]
Could you expand on the envisioned attack?

I'm guessing that the attacker is a same-site cross-origin page within the same BCG, and the result is that they might be able to know whether a same-site cross-origin page has been visited?

**Comment by annevk** [comment]
E.g., say attacker.example knows example.com sets the header but unknown.example.com does not. It first frames unknown.example.com and then example.com and times that. It could first have fetched them to be able to subtract network time.

**Comment by domenic** [comment]
Sorry, that isn't really clear to me... the timing differs between visited and unvisited pages anyway, so if this is a timing attack, I don't see how origin isolation changes things.

**Comment by annevk** [comment]
That's a good point. I haven't been able to come up with a better vector. Coupled with the fact that we are already incentivized to replace browsing context groups whenever possible this probably won't be an issue going forward.
