### ISSUE TITLE
Naming this effort

### ISSUE THREAD

**Issue by domenic** [WICG/origin-isolation#5]
See https://github.com/whatwg/html/issues/4872#issuecomment-555226968 for why "origin isolation" may or may not be the best name.

**Comment by annevk** [comment]
Bikeshed: immutable origin. (As origin being mutable in realms in window agents is the reason we're in this mess, I realized twice more today.)

**Comment by domenic** [comment]
I like that...

It's perhaps less obvious to web developers that making your origin immutable causes the scope of memory-sharing to change to same-origin instead of same-site. But it makes sense once you explain it. And maybe if we pull off https://github.com/whatwg/html/issues/4920 then we don't even need to explain it.

**Comment by domenic** [comment]
Especially as of https://github.com/domenic/origin-isolation/commit/fabdc7c3436d4d2807b7f2afcffd66e331b99b59, I've come to accept origin isolation. So, I'll close this for now.
